//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekDayConsumer.Console.ServiceWeekDay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWeekDay.IServiceWeekDay")]
    public interface IServiceWeekDay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeekDay/GetWeekDay", ReplyAction="http://tempuri.org/IServiceWeekDay/GetWeekDayResponse")]
        string GetWeekDay(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeekDay/GetWeekDay", ReplyAction="http://tempuri.org/IServiceWeekDay/GetWeekDayResponse")]
        System.Threading.Tasks.Task<string> GetWeekDayAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWeekDayChannel : WeekDayConsumer.Console.ServiceWeekDay.IServiceWeekDay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWeekDayClient : System.ServiceModel.ClientBase<WeekDayConsumer.Console.ServiceWeekDay.IServiceWeekDay>, WeekDayConsumer.Console.ServiceWeekDay.IServiceWeekDay {
        
        public ServiceWeekDayClient() {
        }
        
        public ServiceWeekDayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWeekDayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWeekDayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWeekDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWeekDay(System.DateTime date) {
            return base.Channel.GetWeekDay(date);
        }
        
        public System.Threading.Tasks.Task<string> GetWeekDayAsync(System.DateTime date) {
            return base.Channel.GetWeekDayAsync(date);
        }
    }
}
